---
- hosts: "localhost"
  connection: "local"
  become: "yes"

  tasks:
  - name: "Install python3-apt with pip"
    pip:
      name: "{{ item }}"
      state: present
    with_items:
      - python-distutils
      - python-distutils-extra
      - python-apt
  - name: "Add bash completion"
    import_role:
      name: "giovtorres.bash-completion"
...